{
 "title": "Server Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_cpu\", job!=\"prometheus\"}, instance)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu{instance=\"$host\"}, cpu)"
   }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "TOTAL OF HTTP 200",
   "type": "singlestat",
   "description": "2xx Success",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_requests_total{code=\"200\"}"
    }
   ]
  },
  {
   "title": "TOTAL OF HTTP 400",
   "type": "singlestat",
   "description": "4xx Client Error",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_requests_total{code=\"400\"}"
    }
   ]
  },
  {
   "title": "All Cores - total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE",
   "type": "graph",
   "description": "On Linux at least, the load average and CPU utilization are actually two different things. Load average is a measurement of how many tasks are waiting in a kernel run queue (not just CPU time but also disk activity) over a period of time.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "TOTAL OF HTTP 300",
   "type": "singlestat",
   "description": "3xx Redirection",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_requests_total{code=\"300\"}"
    }
   ]
  },
  {
   "title": "TOTAL OF HTTP 500",
   "type": "singlestat",
   "description": "5xx Server Error",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_requests_total{code=\"500\"}"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"user\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "RAM STATUT",
   "type": "graph",
   "description": "Mem cache is oversized ? Run : \n```\nsync; echo 3 > /proc/sys/vm/drop_caches\n```",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "% of total" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal - node_memory_Buffers - node_memory_MemFree - node_memory_Cached) / node_memory_MemTotal) * 100",
     "legendFormat": "Mem Use"
    },
    {
     "expr": "((node_memory_Buffers + node_memory_Cached) / node_memory_MemTotal) * 100",
     "legendFormat": "Mem Buffer + cache"
    },
    {
     "expr": "(node_memory_MemFree / node_memory_MemTotal) * 100",
     "legendFormat": "Mem Free"
    }
   ]
  },
  {
   "title": "$host - OVERALL CPU UTILIZATION",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "% of total" }
   ],
   "targets": [
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    },
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "DISK WRITE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "node_disk_bytes_written", "legendFormat": "Bytes Written" }
   ]
  },
  {
   "title": "NETWORK IN/OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{device!=\"lo\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_bytes{device!=\"lo\"}[1m])",
     "legendFormat": "In: {{ device }}"
    }
   ]
  },
  {
   "title": "DISK READ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "node_disk_bytes_read", "legendFormat": "Bytes Read" }
   ]
  }
 ]
}